version: "3"
services:
  front:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    environment:
      REACT_APP_NCP_CLOUD_ID: ${REACT_APP_NCP_CLOUD_ID}
    stdin_open: true
    tty: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx_proxy
    ports:
      - "80:80"

  back:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
    environment:
      JUSTUS_MYSQL_HOST: ${JUSTUS_MYSQL_HOST}
      JUSTUS_MYSQL_PORT: 3306
      JUSTUS_MYSQL_USER: ${JUSTUS_MYSQL_USER}
      JUSTUS_MYSQL_PASSWORD: ${JUSTUS_MYSQL_PASSWORD}
      JUSTUS_MYSQL_DATABASE: ${JUSTUS_MYSQL_DATABASE}
      JUSTUS_ENTITIY_PATH: /../**/*.entity.{js,ts}
      JUSTUS_MYSQL_SYNC: 1
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      NAVER_CALLBACK_URL: ${NAVER_CALLBACK_URL}
      JWT_SECRET: ${JWT_SECRET}
      NCP_OBJECT_STORAGE_ENDPOINT: ${NCP_OBJECT_STORAGE_ENDPOINT}
      NCP_OBJECT_STORAGE_REGIN: ${NCP_OBJECT_STORAGE_REGIN}
      NCP_ACCESSKEY_ID: ${NCP_ACCESSKEY_ID}
      NCP_SECRET_ACCESSKEY: ${NCP_SECRET_ACCESSKEY}
      NCP_OBJECT_STORAGE_BUCKET: ${NCP_OBJECT_STORAGE_BUCKET}
      NCP_OBJECT_STORAGE_PATH: ${NCP_OBJECT_STORAGE_PATH}
      NODE_ENV: ${NODE_ENV}
      DEV_REDIRECT_URL: http://localhost:3000/
      PROD_REDIRECT_URL: /
      FRONT_LOCALHOST: http://localhost:3000
      JUSTUS_BASE_IMG: ${JUSTUS_BASE_IMG}
      JUSTUS_GROUP_BASE_IMG: ${JUSTUS_GROUP_BASE_IMG}
      JUSTUS_USER_BASE_IMG: ${JUSTUS_USER_BASE_IMG}

  mysql:
    build: ./mysql
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
