version: "3"
services:
  front:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    stdin_open: true
    tty: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  back:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: justus

  mysql:
    build: ./mysql
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: justus
