export const toastMessage = {
  requiredUserName: "닉네임은 반드시 입력해야 합니다.",
  requiredTitle: "제목을 입력해 주세요.",
  requiredDate: "날짜를 선택해 주세요.",
  requiredLocate: "장소를 입력해 주세요.",
  noSearchList: "검색 결과가 존재하지 않습니다.",
  requiredGroupName: "그룹 이름은 반드시 입력해야 합니다.",
  clipboardSuccess: "클립보드에 복사되었습니다.",
  succeedMakeAlbum: (albumName: string) => `${albumName} 앨범이 생성되었습니다.`,
  failedMakeAlbum: "앨범 생성에 실패했습니다.",
  succeedUpdateAlbum: "앨범 정보가 수정되었습니다.",
  failedUpdateAlbum: "앨범 수정에 실패했습니다.",
  succeedRemoveAlbum: "앨범이 삭제되었습니다.",
  failedRemoveAlbum: "앨범 삭제에 실패했습니다.",
  succeedMakeGroup: (groupName: string) => `${groupName} 그룹 생성에 성공했습니다.`,
  failedMakeGroup: "그룹 생성에 실패했습니다.",
  succeedQuitGroup: (groupName: string) => `${groupName} 그룹에서 탈퇴했습니다.`,
  failedQuitGroup: "그룹 탈퇴에 실패했습니다.",
  succeedJoinGroup: "그룹에 참여했습니다.",
  failedJoinGroup: "그룹 참여에 실패했습니다.",
  succeedUpdateGroup: "그룹 정보가 수정되었습니다.",
  failedUpdateGroup: "그룹 정보 수정에 실패했습니다.",
  succeedMakePost: "게시글이 생성되었습니다.",
  failedMakePost: "게시글 생성에 실패했습니다.",
  succeedRemovePost: "게시글이 삭제되었습니다",
  failedRemovePost: "게시글 삭제에 실패했습니다.",
  succeedUpdatePost: "게시글이 수정되었습니다.",
  failedUpdatePost: "게시글 수정에 실패했습니다.",
  succeedUpdateProfile: "회원 정보가 수정되었습니다.",
  failedUpdateProfile: "회원 정보 수정에 실패했습니다.",
};

export const modal = {
  CreateGroupModal: "CreateGroupModal",
  JoinGroupModal: "JoinGroupModal",
  UploadAddressModal: "UploadAddressModal",
  PostCreateModal: "PostCreateModal",
  PostUpdateModal: "PostUpdateModal",
  PostDeleteModal: "PostDeleteModal",
  AddGroupModal: "AddGroupModal",
  UpdateAlbumModal: "UpdateAlbumModal",
  DeleteAlbumModal: "DeleteAlbumModal",
  GroupSettingModal: "GroupSettingModal",
  GroupInfoModal: "GroupInfoModal",
  PostShowModal: "PostShowModal",
};
