const groupModalAction = {
  SET_CLICKED_TARGET: "SET_CLICKED_TARGET",
  OPEN_CREATE_GROUP_MODAL: "OPEN_CREATE_GROUP_MODAL",
  CLOSE_CREATE_GROUP_MODAL: "CLOSE_CREATE_GROUP_MODAL",
  OPEN_JOIN_GROUP_MODAL: "OPEN_JOIN_GROUP_MODAL",
  CLOSE_JOIN_GROUP_MODAL: "CLOSE_JOIN_GROUP_MODAL",
  OPEN_SETTING_GROUP_MODAL: "OPEN_SETTING_GROUP_MODAL",
  CLOSE_SETTING_GROUP_MODAL: "CLOSE_SETTING_GROUP_MODAL",
};

export default groupModalAction;
