const groupAction = {
  ADD_GROUP: "ADD_GROUP",
  SET_SELECTED_GROUP: "SET_SELECTED_GROUP",
  DELETE_GROUP: "DELETE_GROUP",
  // SET_ALL_GROUPS: "SET_ALL_GROUPS",
  MOVE_POST: "MOVE_POST",
};

export default groupAction;
