const modalAction = {
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SET_SELECTED_ALBUM: "SET_SELECTED_ALBUM",
  SELECT_POST_REQUEST: "SELECT_POST_REQUEST",
  SELECT_POST_FAILED: "SELECT_POST_FAILED",
  SET_CLUSTERED_MARKER: "SET_CLUSTERED_MARKER",
  SET_PROFILE_WRAPPER_MODAL_OPENED: "SET_PROFILE_WRAPPER_MODAL_OPENED",
  SET_ALBUM_SETTING_WRAPPER_MODAL_IDX: "SET_ALBUM_SETTING_WRAPPER_MODAL_IDX",
};

export default modalAction;
