name: dev

on:
  push:
    branches: [develop]

env:
  DOCKER_IMAGE_NAME: soosungp33

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Node Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}/dev_node:latest

      - name: React Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}/dev_react:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: ssh connect & production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCLOUD_DEV_HOST_IP }}
          username: ${{ secrets.NCLOUD_DEV_USERNAME }}
          password: ${{ secrets.NCLOUD_DEV_PASSWORD }}
          port: ${{ secrets.NCLOUD_DEV_PORT }}
          script: |
            cd ~
            docker-compose pull
            docker-compose up --force-recreate --build -d
            docker rmi $(docker images -f "dangling=true" -q)
